### ISSUE TITLE
Widows only

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [bitbeans/dnscrypt-measurement#2]
It should be specified on the main page that this is Windows only.
I didn’t notice the first line that says **dnscrypt-measurement.exe**.

So I downloaded the file and saw the .exe file when I unzipped it.
That doesn’t help me on a Mac.

**Comment by bitbeans** [comment]
@GitTheHellOutaHere please try https://github.com/bitbeans/DnsCrypt.Toolbox/releases/tag/0.2.0

**Comment by GitTheHellOutaHere** [comment]
Thanks, but I’ve decided all this mucking about with DNS alternates is just too troublesome, unnecessary and a waste of time. I didn’t have many problems before when I manually entered DNS addresses directly into the DNS Servers pane.

I’m really not interested in using software where I have to tweak its config file and hope I don’t screw up the syntax or permissions.

Dnscrypt-osxclient was simple - install and run.
It may not have had all the features of dnscrypt-proxy, but it worked and was straightforward.
